### ISSUE TITLE
broken pipe when ownCloud refuses upload

### ISSUE THREAD

**Issue by michielbdejong** [Decentralized-Sharing-Working-Group/server-to-server#25]
When the If-Match header is not matched, ownCloud immediately responds with a 412 response, before the whole file upload is streamed. This leads to the following error:

```
     'content-length': '312',
     connection: 'close',
     'content-type': 'application/xml; charset=utf-8' },
  responseBody: '<?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>Sabre\\DAV\\Exception\\PreconditionFailed</s:exception>\n  <s:message>An If-Match header was specified, but none of the specified the ETags matched.</s:message>\n  <s:header>If-Match</s:header>\n</d:error>\n' }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)
```

**Comment by michielbdejong** [comment]
to reproduce, simply try to upload to the same remote filename twice
